01. App/PixelBucketWorld/ViewModels/MessageVMs/MessageViewModel.cs
using PixeBucketWorld.Data.Models;
using PixelBucketWorld.Consts.Numbers;

namespace PixelBucketWorld.ViewModels.MessagesVMs
{
    public class MessageViewModel
    {
        public MessageViewModel(InvitationalMessage  invitationalMessage)
        {
            this.ContestId = invitationalMessage.ContestId;
            this.Content = invitationalMessage.Content;
            this.Title = invitationalMessage.Title;
            this.SenderEmail = invitationalMessage.Sender.Email;
            this.ReceiverEmail = invitationalMessage.Receiver.Email;
            this.IsContestBeforePhaseII = invitationalMessage.Contest.CurrentPhase.Id < PhaseConsts.TRANSITION;
            this.IsContestBeforePhaseI = invitationalMessage.Contest.CurrentPhase.Id < PhaseConsts.PHASE_ONE;

            if (invitationalMessage.InvitationDate.Hour >= 12)
            {
                this.Date = invitationalMessage.InvitationDate.ToString("MM/dd/yy hh/mm/ss PM");
            }
            else
            {
                this.Date = invitationalMessage.InvitationDate.ToString("MM/dd/yy hh/mm/ss AM");
            }
        }

        public bool IsUserJuror { get; set; }

        public bool IsContestBeforePhaseI { get; set; }

        public bool IsContestBeforePhaseII { get; set; }

        public bool isContestAccepted { get; set; }

        public string ReceiverEmail { get; set; }

        public string SenderEmail { get; set; }

        public int ContestId { get; set; }

        public string Content { get; set; }

        public string Title { get; set; }

        public string Date { get; set; }
    }
}

01. App/PixelBucketWorld/Areas/PBW/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PixeBucketWorld.Data.Models;
using PixelBucketWorld.Services;
using PixelBucketWorld.Services.Contracts;
using PixelBucketWorld.ViewModels.MessagesVMs;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PixelBucketWorld.Areas.PBW.Controllers
{
    [Area("PBW")]
    [Authorize]
    public class MessagesController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly ILoggingService loggingService;
        private readonly IUnitOfWork unitOfWork;

        public MessagesController(UserManager<User> userManager, ILoggingService loggingService, IUnitOfWork unitOfWork)
        {
            this.userManager = userManager;
            this.loggingService = loggingService;
            this.unitOfWork = unitOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> GetUserMessages(int id)
        {
            var user = await userManager.FindByIdAsync(id.ToString());

            var messages = await this.unitOfWork.MessageService.GetUserInvitationalMessagesAsync(user.Id);

            var messageNotificationsVM = messages.Select(m => new MessageNotificationViewModel(m));

            return View(messageNotificationsVM);
        }

        [HttpGet]
        public async Task<IActionResult> Get(int id)
        {
            var message = await this.unitOfWork.MessageService.GetByIdAsync(id);
            var user = await userManager.GetUserAsync(this.User);
          

            if(message.ReceiverId != user.Id)
            {
                return View("PageNotFound");
            }

            var messageVM = new MessageViewModel(message);

            var userJurorLink = await this.unitOfWork.ContestJurorLinkService.GetAsync(user.Id, message.ContestId);

            if(userJurorLink == null)
            {
                var userParticipantLink = await this.unitOfWork.ContestParticipantLinkService.GetAsync(user.Id, message.ContestId);

                if(userParticipantLink==null)
                {
                    throw new InvalidOperationException();
                }

                messageVM.isContestAccepted = userParticipantLink.IsAccepted.Value;
            }
            else
            {
                messageVM.isContestAccepted = userJurorLink.IsAccepted;
                messageVM.IsUserJuror = true;
            }

            return View(messageVM);
        }
    }
}

01. App/PixelBucketWorld/Areas/PBW/Views/Messages/Get.cshtml
@model MessageViewModel

<h3>@Model.Title</h3>
<p>from: @Model.SenderEmail</p>
<p>to: @Model.ReceiverEmail</p>
<p>@Model.Content</p>
<form method="get">
    <button type="submit" asp-area="PBW" asp-route-id="@Model.ContestId" asp-action="Details" asp-controller="Contests">View details</button>
</form>
@if (Model.IsUserJuror)
{
    @if (!Model.isContestAccepted && Model.IsContestBeforePhaseI)
    {
        <form method="post">
            <button type="submit" class="btn-success" asp-area="PBW" asp-action="AcceptContestInvitation" asp-controller="Users"
                    asp-route-ContestId="@Model.ContestId" asp-route-UserId="@this.User.FindFirst(ClaimTypes.NameIdentifier).Value">
                Accept!
            </button>
            <p class="text-secondary"><strong>NOTE:</strong> You must accept the invitation to participate in the contest.</p>
        </form>
    }
}
else
{
    if (!Model.isContestAccepted && Model.IsContestBeforePhaseII)
    {
        <form method="post">
            <button type="submit" class="btn-success" asp-area="PBW" asp-action="AcceptContestInvitation" asp-controller="Users"
                    asp-route-ContestId="@Model.ContestId" asp-route-UserId="@this.User.FindFirst(ClaimTypes.NameIdentifier).Value">
                Accept!
            </button>
            <p class="text-secondary"><strong>NOTE:</strong> You must accept the invitation to participate in the contest.</p>
        </form>
    }
}

01. App/PixelBucketWorld/Areas/PBW/Views/Messages/GetUserMessages.cshtml
@model IEnumerable<MessageNotificationViewModel>

@if (TempData["invitationAccepted"] !=null)
{
    <p class="text-success">@TempData["invitationAccepted"]</p>
}
<div class="table-responsive">
    <table class="table">
        <tbody>
            @foreach (var message in Model)
            {
                <tr>
                    <td class="action"><input type="checkbox" /></td>
                    <td class="action"><i class="fa fa-star-o"></i></td>
                    <td class="action"><i class="fa fa-bookmark-o"></i></td>
                    <td class="name"><a href="#">Organisers team</a></td>
                    <td class="subject"><a asp-area="PBW" asp-action="Get" asp-controller="Messages" asp-route-id="@message.Id">@message.Title</a></td>
                    <td class="time">@message.Date</td>
                </tr>
            }
        </tbody>
    </table>
</div>