01. App/PixelBucketWorld/Areas/PBW/Controllers/ContestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PixeBucketWorld.Data.Models;
using PixeBucketWorld.Data.Models.FilteringModels;
using PixeBucketWorld.Data.Models.Logging.Enums;
using PixelBucketWorld.Consts.Numbers;
using PixelBucketWorld.Consts.Strings;
using PixelBucketWorld.Helpers;
using PixelBucketWorld.Map;
using PixelBucketWorld.Services;
using PixelBucketWorld.Services.Contracts;
using PixelBucketWorld.ViewModels.ContestVMs;
using PixelBucketWorld.ViewModels.PhotoAssessmentVMs;
using PixelBucketWorld.ViewModels.PhotoVMs;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PixelBucketWorld.Areas.PBW.Controllers
{
    [Area("PBW")]
    public class ContestsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly UserManager<User> userManager;
        private readonly ILoggingService loggingService;
        private readonly IWebHostEnvironment webHostingEnvironment;

        public ContestsController(IUnitOfWork unitOfWork, UserManager<User> userManager, ILoggingService loggingService, IWebHostEnvironment webHostingEnvironment)
        {
            this.unitOfWork = unitOfWork;
            this.userManager = userManager;
            this.loggingService = loggingService;
            this.webHostingEnvironment = webHostingEnvironment;
        }

        [HttpGet]
        [Authorize(Roles = UserRoleConsts.ORGANISER)]
        public async Task<IActionResult> Create()
        {
            var createContestVM = new CreateContestViewModel();

            await this.FillCreateView(createContestVM);

            return View(createContestVM);
        }

        [HttpPost]
        [Authorize(Roles = UserRoleConsts.ORGANISER)]
        public async Task<IActionResult> Create(CreateContestViewModel model, IEnumerable<int> usersToInvite, IEnumerable<int> usersForJury)
        {
            if (ModelState.IsValid)
            {
                var sameUsers = usersToInvite.Intersect(usersForJury).ToList();

                if (sameUsers.Any())
                {
                    List<string> users = new List<string>();

                    foreach (var userId in sameUsers)
                    {
                        var user = await this.unitOfWork.UserService.GetByIdAsync(userId);
                        users.Add(user.UserName);
                    }


                    if (users.Count == 1)
                    {
                        ModelState.AddModelError("", $"User {users[0]} can be added as jury or participant, but not both");
                    }
                    else
                    {
                        ModelState.AddModelError("", $"User {string.Join(',', users)} can be added as jury or participant, but not both");
                    }

                    await this.FillCreateView(model);

                    return View(model);
                }


                var contest = InputMapper.Map(model);

                if (model.UploadedCoverPhoto != null)
                {
                    //var uploadsFolderShortcut = Path.Combine("wwwroot", "images", "UploadedPhotos");
                    var uploadsFolder = Path.Combine(webHostingEnvironment.WebRootPath, "images", "ContestPhotos");

                    //Using guid cause more than one photo with the same name can be uploaded
                    var uniqueFileName = Guid.NewGuid().ToString() + "_" + model.UploadedCoverPhoto.FileName;

                    var filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    //var filePathShortcut = Path.Combine(uploadsFolderShortcut, uniqueFileName);

                    var filePathShortcut = $"/images/ContestPhotos/{uniqueFileName}";

                    await Uploader.Upload(model.UploadedCoverPhoto, filePath);

                    contest.PhotoUrl = filePathShortcut;
                }
                else if(model.ExistingCoverPhoto != null)
                {
                    var photoUrl = $"/images/ContestPhotos/{model.ExistingCoverPhoto.FileName}";

                    if(!(await this.unitOfWork.PhotoService.DoesCoverPhotoExistsLocally(photoUrl)))
                    {
                        ModelState.AddModelError("", "Please attach existing photo! Navigate to wwwroot/ContestPhotos");

                        await this.FillCreateView(model);

                        return View(model);
                    }

                    contest.PhotoUrl = photoUrl;
                }
                else if(model.PhotoUrl != null)
                {
                    var responseMessage =  await this.unitOfWork.PhotoService.GetRequestResponse(model.PhotoUrl);

                    if (responseMessage == null)
                    {
                        ModelState.AddModelError("", "The URL you've provided is not valid!");

                        await this.FillCreateView(model);

                        return View(model);
                    }

                    var isValid = this.unitOfWork.PhotoService.IsResponseContentTypeValidImageFormat(responseMessage);

                    if (!isValid)
                    {
                        ModelState.AddModelError("", "Only .jpeg and .png formats are accepted");

                        await this.FillCreateView(model);

                        return View(model);
                    }

                    contest.PhotoUrl = model.PhotoUrl;
                }
                else
                {
                    contest.PhotoUrl = "/images/ContestPhotos/PixelBucketWorld.jpg";
                }

                await this.unitOfWork.ContestService.CreateAsync(contest);

                await this.unitOfWork.SaveAsync();

                var sender = await userManager.GetUserAsync(this.User);

                if (sender == null)
                {
                    throw new ArgumentNullException();
                }

                if (usersToInvite != null)
                {
                    //Won't find correct last contest in next methods because SaveChanges() is not called yet??? how to fix
                    await this.unitOfWork.ContestParticipantLinkService.CreateDefaultContestParticipantLinks(usersToInvite, contest.Id);

                    await this.unitOfWork.MessageService.SendParticipantsInvitationalMessageAsync(usersToInvite, contest.Id, sender.Id);

                    await this.unitOfWork.SaveAsync();
                }

                if (usersForJury != null)
                {
                    await this.unitOfWork.MessageService.SendJuryInvitationalMessageAsync(usersForJury, contest.Id, sender.Id);

                    await this.unitOfWork.ContestJurorLinkService.CreateDefaultContestJurorLinks(usersForJury, contest.Id);

                    await this.unitOfWork.SaveAsync();
                }

                await this.loggingService.LogInformationAsync(InformationLogEvent.INSERT_ITEM, null, contest);

                TempData["contestSuccessfullyCreated"] = $"Contest \"{contest.Name}\" has been successfully created";

                return RedirectToAction("OrganiserDashboard", "Users", new { id = sender.Id });
            }

            await this.FillCreateView(model);

            return View(model);
        }

        private async Task FillCreateView(CreateContestViewModel createContestVM)
        {
            //var categories = await this.unitOfWork.ContestService.GetCategoriesAsync();
            var categories = await this.unitOfWork.CategoryService.GetAllAsync();
            //var types = await this.unitOfWork.ContestService.GetTypesAsync();
            var types = await this.unitOfWork.ContestTypesService.GetAllAsync();

            foreach (var category in categories)
            {
                createContestVM.Categories.Add(new SelectListItem { Text = category.Name, Value = $"{category.Id}" });
            }

            foreach (var type in types)
            {
                createContestVM.Types.Add(new SelectListItem { Text = type.Name, Value = $"{type.Id}" });
            }

            var filteringCriterias = new UserFilteringCriterias();
            filteringCriterias.RoleSelectOptions.Add(UserRoles.PARTICIPANT_ROLE_ID);
            var allParticipantUsers = await this.unitOfWork.UserService.GetAsync(filteringCriterias);
            createContestVM.UsersToInvite.AddRange(allParticipantUsers);

            var userFilteringCriterias = new UserFilteringCriterias();
            userFilteringCriterias.RankSelectOptions.Add(RankConsts.MASTER);
            userFilteringCriterias.RankSelectOptions.Add(RankConsts.WISE_AND_BENEVOLENT_PHOTO_DICTATOR);
            var participantsEligibleJury = await this.unitOfWork.UserService.GetAsync(userFilteringCriterias);
            createContestVM.Jury.AddRange(participantsEligibleJury);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var contest = await this.unitOfWork.ContestService.GetByIdAsync(id);

            if (contest.CurrentPhase.Id == PhaseConsts.PRESTART)
            {
                ContestPhasePrestartViewModel phasePrestartVM = new ContestPhasePrestartViewModel(contest);
                return View("PhasePrestartDetails", model: phasePrestartVM);
            }
            else if (contest.CurrentPhase.Id == PhaseConsts.PHASE_ONE) //must be changed to 2
            {
                var phaseIDetaislVM = new ContestPhaseOneDetailsViewModel(contest);
                return View("PhaseOneDetails", model: phaseIDetaislVM);
            }
            else if (contest.CurrentPhase.Id == PhaseConsts.PHASE_TWO)
            {
                var phaseTwoDetailsVM = new ContestPhaseTwoDetailsViewModel(contest);

01. App/PixelBucketWorld/Areas/PBW/Views/Contests/Create.cshtml
@model CreateContestViewModel

<form enctype="multipart/form-data" method="post" asp-area="PBW" asp-action="Create">
    <div class="form-group">
        <label asp-for="@Model.Title"></label>
        <input asp-for="@Model.Title" class="form-control" />
        <span asp-validation-for="@Model.Title" class="text-danger"></span>
    </div>
    <div>
        <select class="form-select" name="category" asp-items="@Model.Categories">
            <option>Please select category</option>
        </select>
    </div>
    <div>
        <select class="form-select" name="type" id="contestTypes" asp-items="@Model.Types">
            <option>Please select type</option>
        </select>
        <div id="inviteUsersForm" style="display:none">
            <p>Users to invite</p>
            @foreach (var userToInvite in Model.UsersToInvite)
            {
                <label asp-for="@userToInvite">@userToInvite.UserName</label>
                <input type="checkbox" value="@userToInvite.Id" id="@userToInvite.Id+userToInvite" name="usersToInvite" />
            }
        </div>
        <input style="display:none" type="button" id="changeInviteBtn" value="Change users to invite">
    </div>
    <div class="form-group">
        <label asp-for="@Model.PhaseOneStartingDate">Phase I starting date</label>
        <input asp-for="@Model.PhaseOneStartingDate" class="form-control" />
        <span asp-validation-for="@Model.PhaseOneStartingDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.PhaseOneFinishingDate">Phase I ending date</label>
        <input asp-for="@Model.PhaseOneFinishingDate" class="form-control" />
        <span asp-validation-for="@Model.PhaseOneFinishingDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.PhaseTwoStartingDate">Phase II starting date</label>
        <input asp-for="@Model.PhaseTwoStartingDate" class="form-control" />
        <span asp-validation-for="@Model.PhaseTwoStartingDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.PhaseTwoFinishingDate">Phase II ending date</label>
        <input asp-for="@Model.PhaseTwoFinishingDate" class="form-control" />
        <span asp-validation-for="@Model.PhaseTwoStartingDate" class="text-danger"></span>
    </div>
    <div id="juryToInviteForm">
        <p>Jury to invite</p>
        @if (!Model.Jury.Any())
        {
            <p>No eligible users to invite.</p>
        }
        else
        {
            @foreach (var userForJury in Model.Jury)
            {
                <label asp-for="@userForJury">@userForJury.UserName</label>
                <input type="checkbox" value="@userForJury.Id" id="@userForJury.Id+userForJury" name="usersForJury" />
            }
        }
    </div>

    <span class="text-secondary"><strong>NOTE: </strong>Uploading cover photo is optional</span>
    <p>Choose uploading method:</p>
    <div>
        <button type="button" id="newPhoto">New photo</button>
        <button type="button" id="photoUrl">Photo URL</button>
        <button type="button" id="existingPhoto">Existing photo</button>
    </div>
    <div id="uploadingPhotoDiv" style="display:none">
        <label asp-for="UploadedCoverPhoto">Upload new photo:</label>
        <input id="uploadNewPhotoInput" class="form-control-file" asp-for="UploadedCoverPhoto" />
    </div>

    <div id="photoUrlInputDiv" style="display:none">
        <label asp-for="PhotoUrl">Place the photo URL:</label>
        <input class="form-control" asp-for="PhotoUrl" id="photoUrlInput" placeholder="Paste the URL of an existing photo" />
    </div>

    <div id="previouslyUploadedPhotosDiv" style="display:none">
        <label asp-for="ExistingCoverPhoto">Choose from previously uploaded photos:</label>
        <input id="uploadExistingPhotoInput" class="form-control-file" asp-for="ExistingCoverPhoto" />
    </div>
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>

    <input type="submit" asp-area="PBW" asp-action="Create" asp-controller="Contests" value="Submit" />
</form>

@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/allUsers.js"></script>
    <script src="~/js/contestUploadingPhoto.js"></script>
}

01. App/PixelBucketWorld/Areas/PBW/Views/Contests/Details.cshtml
@Model ContestPhaseOneViewModel 

01. App/PixelBucketWorld/Areas/PBW/Views/Contests/PhaseFinishedDetails.cshtml
@model ContestPhaseFinishedViewModel


@await Html.PartialAsync("GeneralPhaseDetailsPartial", model: Model) 

@if (this.User.IsInRole("Participant") && !Model.IsUserJuror)
{
    <h2>My assessment</h2>
    @await Html.PartialAsync("_AssessmentCardPartial", model: Model.CurrentUserPhotoAssessment);

    <hr>
}

<h1>Winners assessments</h1>
<h3>1st place</h3>
<div class="container">
    <div class="row">
        @foreach (var photo in Model.FirstPlaceWinnersAssessments)
        {
            @await Html.PartialAsync("_AssessmentCardPartial", model: photo)
        }
    </div>
</div>
<h3>2nd place</h3>
<div class="container">
    <div class="row">
        @foreach (var photo in Model.SecondPlaceWinnersAssessments)
        {
            @await Html.PartialAsync("_AssessmentCardPartial", model: photo)
        }
    </div>
</div>
<h3>3rd place</h3>
<div class="container">
    <div class="row">
        @foreach (var photo in Model.ThirdPlaceWinnersAssessments)
        {
            @await Html.PartialAsync("_AssessmentCardPartial", model: photo)
        }
    </div>
</div>

<hr>

<h2>Other photo asssessments</h2>
<div class="container">
    <div class="row">
        @foreach (var photo in Model.LoosersPhotoAssessments)
        {
            @await Html.PartialAsync("_AssessmentCardPartial", model: photo)
        }
    </div>
</div>

01. App/PixelBucketWorld/Areas/PBW/Views/Contests/PhasePrestartDetails.cshtml
@model ContestPhasePrestartViewModel
@inject UserManager<User> userManager;
@{
    var user = await this.userManager.GetUserAsync(this.User);
    var jurorLink = Model.JurorLinks.FirstOrDefault(j => j.UserId == user.Id);
    var inviteeLink = Model.InviteesLinks.FirstOrDefault(p => p.UserId == user.Id);
}

@await Html.PartialAsync("GeneralPhaseDetailsPartial", model: Model); 
<p>Remaining time until end of the phase: <span id="remainingTimeCurrPhase">@Model.CurrentPhaseDiffMillisec</span></p>
<p>Remaining time until Phase I: <span id="remainingTimeNextPhase">@Model.CurrentNextPhaseDiffInMillsec</span></p>

@if (this.User.IsInRole(UserRoleConsts.ORGANISER))
{
    <span class="text-warning">The contest will start soon! After the first participants upload photo you will be able to view it and decide 
    how to rate it in Phase II! Good luck!</span>
}
else
{
    @if (jurorLink != null)
    {
        if (jurorLink.IsAccepted)
        {
            <p>Hi juror! The contest will start soon! You can check the uploaded photos of the participants in Phase II. Good luck!</p>
        }
        else
        {
            <p>Congratulations! You've been invited as jury for this contest!</p>
            <form method="post">
                <button type="submit" class="btn-success" asp-area="PBW" asp-action="AcceptContestInvitation" asp-controller="Users"
                        asp-route-ContestId="@Model.ContestId" asp-route-UserId="@jurorLink.UserId">
                    Accept!
                </button>
                <p class="text-secondary"><strong>NOTE:</strong> You must accept the invitation to participate in the contest.</p>
            </form>
        }
    }
    else if (inviteeLink != null)
    {
        @if (inviteeLink.IsAccepted.HasValue && inviteeLink.IsAccepted.Value)
        {
            <p>Hi invitee! The contest will start soon! We are waiting for your photo!</p>
        }
        else
        {
            <form method="post">
                <p class="text-secondary"><strong>NOTE:</strong> You may accept the invitation to participate as juror in the contest.</p>
                <button type="submit" class="btn-success" asp-area="PBW" asp-action="AcceptContestInvitation" asp-controller="Users"
                        asp-route-ContestId="@Model.ContestId" asp-route-UserId="@inviteeLink.UserId">
                    Accept!
                </button>
            </form>
        }
    }
    else
    {
        <p>Hi participant! The contest will start soon! Please upload your photo in Phase I</p>
    }
}

@section Scripts {
    <script src="~/js/Timers.js"></script>
}

01. App/PixelBucketWorld/Areas/PBW/Views/Contests/PhaseTransitionDetails.cshtml
@model ContestPhaseTransitionViewModel

@await Html.PartialAsync("GeneralPhaseDetailsPartial", model: Model)
<p>Remaining time until Phase II: <span id="remainingTimeNextPhase">@Model.NextPhaseDiffInMillSec</span></p>

<h4>The photos are already uploaded! Soon our jury will review them and choose the final winners! Don't miss it out!</h4>

@if (!Model.UploadedPhotos.Any())
{
    <p>No photos were uploaded to this contest :(</p>
}
else
{
    <h3>See below the uploaded photos</h3>
    @foreach (var photo in Model.UploadedPhotos)
    {
        @await Html.PartialAsync("_PhotoCardPartial", model: photo)
    }
}

@section Scripts{ 
 <script src="~/js/Timers.js"></script>
}

01. App/PixelBucketWorld/Areas/PBW/Views/Contests/PhaseTwoDetails.cshtml
@model ContestPhaseTwoDetailsViewModel
@inject UserManager<User> userManager
@{
    var user = await userManager.GetUserAsync(this.User);
}

@await Html.PartialAsync("GeneralPhaseDetailsPartial", model: Model)

@if (this.User.IsInRole("Participant"))
{
    <p class="text-warning">The contest is in Phase II and the photos are reviewed by the jury.</p>
}
<p>Remaining time until end of the phase: <span id="remainingTimeCurrPhase">@Model.CurrentPhaseDiffInMillisec</span></p>

@if (this.User.IsInRole("Participant") && Model.Jury.All(j => j.Id != user.Id))
{
    @if (@Model.Participants.FirstOrDefault(p => p.Id == user.Id) != null)
    {
        <p class="text-success">Your photo is submitted. You can view final result soon! Good luck!</p>
    }
    else
    {
        @if (!Model.Photos.Any())
        {
            <p>Contest has already started! Our participants will start uploading photos soon! Enjoy and join us with the next contest!</p>
        }
        else
        {
            <p>Contest has already started! Enjoy the photos of our participants and join us on the next contest!</p>
            <div class="container">
                <div class="row">
                    @foreach (var photo in Model.Photos)
                    {
                        @await Html.PartialAsync("_PhotoCardPartial", model: photo);
                    }
                </div>
            </div>
        }
    }
}
else
{
    <div class="container">
        <div class="row">
            @foreach (var photoCardVM in Model.Photos)
            {
                @await Html.PartialAsync("_PhotoToRateCardPartial", model: photoCardVM);
            }
        </div>
    </div>
}

@section Scripts{
    <script src="~/js/Timers.js"></script>
}